# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\MS-Drive\OneDrive - UOU\WORK\Workspace\WORK\PYTHON\python-workspace\sandGroupMaill\ui/root.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(522, 388)
        MainWindow.setMinimumSize(QtCore.QSize(465, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listview1 = QtWidgets.QListWidget(self.centralwidget)
        self.listview1.setGeometry(QtCore.QRect(400, 60, 101, 141))
        self.listview1.setStyleSheet("border: 1px solid pink;")
        self.listview1.setDragEnabled(True)
        self.listview1.setDragDropOverwriteMode(True)
        self.listview1.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.listview1.setAlternatingRowColors(False)
        self.listview1.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listview1.setViewMode(QtWidgets.QListView.ListMode)
        self.listview1.setModelColumn(0)
        self.listview1.setObjectName("listview1")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(
            QtCore.Qt.ItemIsSelectable
            | QtCore.Qt.ItemIsEditable
            | QtCore.Qt.ItemIsDragEnabled
            | QtCore.Qt.ItemIsUserCheckable
            | QtCore.Qt.ItemIsEnabled
        )
        self.listview1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listview1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listview1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listview1.addItem(item)
        self.listview2 = QtWidgets.QListWidget(self.centralwidget)
        self.listview2.setGeometry(QtCore.QRect(400, 210, 101, 111))
        self.listview2.setStyleSheet("border: 1px solid pink;")
        self.listview2.setDragEnabled(True)
        self.listview2.setDragDropOverwriteMode(True)
        self.listview2.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.listview2.setAlternatingRowColors(False)
        self.listview2.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listview2.setObjectName("listview2")
        self.pb1 = QtWidgets.QPushButton(self.centralwidget)
        self.pb1.setGeometry(QtCore.QRect(404, 340, 101, 23))
        self.pb1.setObjectName("pb1")
        self.te2 = QtWidgets.QTextEdit(self.centralwidget)
        self.te2.setGeometry(QtCore.QRect(20, 90, 361, 231))
        self.te2.setObjectName("te2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.te1 = QtWidgets.QLineEdit(self.centralwidget)
        self.te1.setGeometry(QtCore.QRect(20, 60, 361, 20))
        self.te1.setObjectName("te1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionghdfhdfh = QtWidgets.QAction(MainWindow)
        self.actionghdfhdfh.setObjectName("actionghdfhdfh")

        self.retranslateUi(MainWindow)
        self.listview1.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.listview1.isSortingEnabled()
        self.listview1.setSortingEnabled(False)
        item = self.listview1.item(0)
        item.setText(_translate("MainWindow", "손민찬"))
        item = self.listview1.item(1)
        item.setText(_translate("MainWindow", "손융은"))
        item = self.listview1.item(2)
        item.setText(_translate("MainWindow", "ccc"))
        item = self.listview1.item(3)
        item.setText(_translate("MainWindow", "ddd"))
        self.listview1.setSortingEnabled(__sortingEnabled)
        self.pb1.setText(_translate("MainWindow", "메일 발송"))
        self.label.setText(_translate("MainWindow", "테스트용 그룹 메일 보내기"))
        self.actionghdfhdfh.setText(_translate("MainWindow", "ghdfhdfh"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
