# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\MS-Drive\OneDrive - UOU\WORK\Workspace\WORK\PYTHON\python-workspace\pythonProject\ui/root.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(465, 424)
        MainWindow.setMinimumSize(QtCore.QSize(465, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.te1 = QtWidgets.QTextEdit(self.centralwidget)
        self.te1.setGeometry(QtCore.QRect(30, 40, 251, 31))
        self.te1.setObjectName("te1")
        self.listview1 = QtWidgets.QListWidget(self.centralwidget)
        self.listview1.setGeometry(QtCore.QRect(320, 40, 101, 151))
        self.listview1.setDragEnabled(True)
        self.listview1.setDragDropOverwriteMode(True)
        self.listview1.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.listview1.setAlternatingRowColors(False)
        self.listview1.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listview1.setViewMode(QtWidgets.QListView.ListMode)
        self.listview1.setModelColumn(0)
        self.listview1.setObjectName("listview1")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(
            QtCore.Qt.ItemIsSelectable
            | QtCore.Qt.ItemIsEditable
            | QtCore.Qt.ItemIsDragEnabled
            | QtCore.Qt.ItemIsUserCheckable
            | QtCore.Qt.ItemIsEnabled
        )
        self.listview1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listview1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listview1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listview1.addItem(item)
        self.listview2 = QtWidgets.QListWidget(self.centralwidget)
        self.listview2.setGeometry(QtCore.QRect(320, 210, 101, 121))
        self.listview2.setDragEnabled(True)
        self.listview2.setDragDropOverwriteMode(True)
        self.listview2.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.listview2.setAlternatingRowColors(False)
        self.listview2.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listview2.setObjectName("listview2")
        self.pb1 = QtWidgets.QPushButton(self.centralwidget)
        self.pb1.setGeometry(QtCore.QRect(340, 370, 75, 23))
        self.pb1.setObjectName("pb1")
        self.te2 = QtWidgets.QTextEdit(self.centralwidget)
        self.te2.setGeometry(QtCore.QRect(30, 90, 251, 231))
        self.te2.setObjectName("te2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionghdfhdfh = QtWidgets.QAction(MainWindow)
        self.actionghdfhdfh.setObjectName("actionghdfhdfh")

        self.retranslateUi(MainWindow)
        self.listview1.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.te1.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Gulim'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">메일 제목 입력</p></body></html>',
            )
        )
        __sortingEnabled = self.listview1.isSortingEnabled()
        self.listview1.setSortingEnabled(False)
        item = self.listview1.item(0)
        item.setText(_translate("MainWindow", "손민찬"))
        item = self.listview1.item(1)
        item.setText(_translate("MainWindow", "손융은"))
        item = self.listview1.item(2)
        item.setText(_translate("MainWindow", "ccc"))
        item = self.listview1.item(3)
        item.setText(_translate("MainWindow", "ddd"))
        self.listview1.setSortingEnabled(__sortingEnabled)
        self.pb1.setText(_translate("MainWindow", "메일 발송"))
        self.actionghdfhdfh.setText(_translate("MainWindow", "ghdfhdfh"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
