# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:/MS-Drive/OneDrive - UOU/WORK/Workspace/WORK/PYTHON/python-workspace/pythonProject/ui/root2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form2):
        Form2.setObjectName("Form2")
        Form2.resize(540, 514)
        self.lw1 = QtWidgets.QListWidget(Form2)
        self.lw1.setGeometry(QtCore.QRect(20, 20, 256, 192))
        self.lw1.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lw1.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lw1.setAlternatingRowColors(True)
        self.lw1.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lw1.setObjectName("lw1")
        item = QtWidgets.QListWidgetItem()
        self.lw1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lw1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lw1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lw1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lw1.addItem(item)
        self.lv1 = QtWidgets.QListView(Form2)
        self.lv1.setGeometry(QtCore.QRect(20, 240, 256, 192))
        self.lv1.setDragEnabled(False)
        self.lv1.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lv1.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lv1.setAlternatingRowColors(True)
        self.lv1.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lv1.setObjectName("lv1")
        self.lw2 = QtWidgets.QListWidget(Form2)
        self.lw2.setGeometry(QtCore.QRect(280, 20, 256, 192))
        self.lw2.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lw2.setAlternatingRowColors(True)
        self.lw2.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lw2.setObjectName("lw2")

        self.retranslateUi(Form2)
        QtCore.QMetaObject.connectSlotsByName(Form2)

    def retranslateUi(self, Form2):
        _translate = QtCore.QCoreApplication.translate
        Form2.setWindowTitle(_translate("Form2", "Form"))
        __sortingEnabled = self.lw1.isSortingEnabled()
        self.lw1.setSortingEnabled(False)
        item = self.lw1.item(0)
        item.setText(_translate("Form2", "aaa"))
        item = self.lw1.item(1)
        item.setText(_translate("Form2", "bbb"))
        item = self.lw1.item(2)
        item.setText(_translate("Form2", "ccc"))
        item = self.lw1.item(3)
        item.setText(_translate("Form2", "ddd"))
        item = self.lw1.item(4)
        item.setText(_translate("Form2", "eee"))
        self.lw1.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form2 = QtWidgets.QWidget()
    ui = Ui_Form2()
    ui.setupUi(Form2)
    Form2.show()
    sys.exit(app.exec_())
