# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\MS-Drive\OneDrive - UOU\WORK\Workspace\WORK\PYTHON\python-workspace\AIR_Html_Converter\libs/Ui\langPop.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(341, 312)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 321, 251))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plw1 = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.plw1.setMinimumSize(QtCore.QSize(0, 0))
        self.plw1.setSizeIncrement(QtCore.QSize(0, 0))
        self.plw1.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plw1.setFont(font)
        self.plw1.setAcceptDrops(True)
        self.plw1.setLineWidth(0)
        self.plw1.setMidLineWidth(0)
        self.plw1.setDragEnabled(True)
        self.plw1.setDragDropOverwriteMode(False)
        self.plw1.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.plw1.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.plw1.setAlternatingRowColors(True)
        self.plw1.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.plw1.setObjectName("plw1")
        self.horizontalLayout.addWidget(self.plw1)
        self.plw2 = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plw2.setFont(font)
        self.plw2.setDragEnabled(True)
        self.plw2.setDragDropOverwriteMode(False)
        self.plw2.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.plw2.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.plw2.setAlternatingRowColors(True)
        self.plw2.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.plw2.setObjectName("plw2")
        self.horizontalLayout.addWidget(self.plw2)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 13, 151, 31))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(178, 13, 151, 31))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "전체 언어"))
        self.label_2.setText(_translate("Form", "선택 언어"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
